// Generated by CoffeeScript 1.6.3
(function() {
  var Engine, Map, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Engine = (function() {
    Engine.prototype.handle = {};

    function Engine(canvas, bgm, sfx) {
      this.handle = {
        canvas: canvas,
        bgm: bgm,
        sfx: sfx
      };
      this.map = new Map();
      this.main(this);
    }

    Engine.prototype.update = function() {
      return this.map.update();
    };

    Engine.prototype.draw = function(handle) {
      return this.map.draw(handle);
    };

    Engine.prototype.main = function(c) {
      var _this = this;
      c.update();
      c.draw(c.handle);
      return requestAnimationFrame(function() {
        return _this.main(c);
      });
    };

    return Engine;

  })();

  if (!root.Game) {
    root.Game = Engine;
  }

  Map = (function() {
    function Map() {
      var i, j;
      this.height = 100;
      this.width = 100;
      this.viewport = {
        x: 0,
        y: 0
      };
      this.data = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= width ? _i < width : _i > width; i = 0 <= width ? ++_i : --_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (j = _j = 0; 0 <= height ? _j < height : _j > height; j = 0 <= height ? ++_j : --_j) {
              _results1.push('.');
            }
            return _results1;
          })());
        }
        return _results;
      })();
    }

    Map.prototype.update = function() {};

    Map.prototype.draw = function(handle) {
      var output, tile, _i, _len, _ref;
      output = '';
      _ref = this.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tile = _ref[_i];
        output += tile.join(' ') + '\n';
      }
      return document.body.innerHTML = output;
    };

    return Map;

  })();

}).call(this);
