// Generated by CoffeeScript 1.6.3
(function() {
  var Engine, Map, Player, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Engine = (function() {
    Engine.prototype.handle = {};

    function Engine(canvas, bgm, sfx) {
      this.handle = {
        canvas: canvas,
        bgm: bgm,
        sfx: sfx
      };
      this.map = new Map();
      this.player = new Player();
      this.main(this);
    }

    Engine.prototype.update = function() {
      this.player.update(this.map);
      return this.map.update();
    };

    Engine.prototype.draw = function(handle) {
      return this.map.draw(handle);
    };

    Engine.prototype.main = function(c) {
      var _this = this;
      c.update();
      c.draw(c.handle);
      return requestAnimationFrame(function() {
        return _this.main(c);
      });
    };

    return Engine;

  })();

  if (!root.Game) {
    root.Game = Engine;
  }

  Map = (function() {
    function Map() {
      var height, i, j, width;
      height = 100;
      width = 100;
      this.viewport = {
        x: 0,
        y: 0,
        height: 9,
        width: 9
      };
      this.data = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= width ? _i < width : _i > width; i = 0 <= width ? ++_i : --_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (j = _j = 0; 0 <= height ? _j < height : _j > height; j = 0 <= height ? ++_j : --_j) {
              _results1.push(Math.random() > 0.8 && '#' || '.');
            }
            return _results1;
          })());
        }
        return _results;
      })();
    }

    Map.prototype.update = function() {};

    Map.prototype.inBounds = function(x, y) {
      return x > 0 && y > 0 && x < this.data.length && y < this.data[0].length;
    };

    Map.prototype.canMove = function(x, y) {
      return this.inBounds(x, y) && this.data[x][y] === '.';
    };

    Map.prototype.updateViewport = function(x, y) {
      this.viewport.x = x - (this.viewport.width >> 1);
      return this.viewport.y = y - (this.viewport.height >> 1);
    };

    Map.prototype.draw = function(handle) {
      var center, i, j, output, _i, _j, _ref, _ref1, _ref2, _ref3;
      output = '';
      center = {
        x: this.viewport.x + (this.viewport.width >> 1),
        y: this.viewport.y + (this.viewport.height >> 1)
      };
      for (i = _i = _ref = this.viewport.y, _ref1 = this.viewport.y + this.viewport.height; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; i = _ref <= _ref1 ? ++_i : --_i) {
        for (j = _j = _ref2 = this.viewport.x, _ref3 = this.viewport.x + this.viewport.width; _ref2 <= _ref3 ? _j < _ref3 : _j > _ref3; j = _ref2 <= _ref3 ? ++_j : --_j) {
          if (this.inBounds(i, j)) {
            output += ((j === center.x && i === center.y) && '@' || this.data[j][i]) + ' ';
          } else {
            output += '  ';
          }
        }
        output += '\n';
      }
      return document.body.innerHTML = output;
    };

    return Map;

  })();

  Player = (function() {
    Player.prototype.keys = [];

    Player.prototype.pos = {
      x: 20,
      y: 20
    };

    Player.prototype.action = {
      attack: 32,
      up: 82,
      down: 72,
      left: 83,
      right: 84
    };

    function Player(handle) {
      var i, k, _i;
      for (i = _i = 0; _i <= 255; i = ++_i) {
        this.keys.push(false);
      }
      k = this.keys;
      document.onkeydown = function(e) {
        return k[e.keyCode] = true;
      };
      document.onkeyup = function(e) {
        return k[e.keyCode] = false;
      };
    }

    Player.prototype.update = function(map) {
      if (this.keys[this.action.up] && map.canMove(this.pos.x, this.pos.y - 1)) {
        this.pos.y--;
      }
      if (this.keys[this.action.down] && map.canMove(this.pos.x, this.pos.y + 1)) {
        this.pos.y++;
      }
      if (this.keys[this.action.left] && map.canMove(this.pos.x - 1, this.pos.y)) {
        this.pos.x--;
      }
      if (this.keys[this.action.right] && map.canMove(this.pos.x + 1, this.pos.y)) {
        this.pos.x++;
      }
      return map.updateViewport(this.pos.x, this.pos.y);
    };

    return Player;

  })();

}).call(this);
